db:
  type: 'postgres'
  host: 'database-2.c934rjf1iqqy.us-east-2.rds.amazonaws.com'
  port: 5432
  username: 'postgres'
  password: 'postgres'
  database: 'postgres'
  synchronize: true

server:
  port: 3001
  scheme: 'http'

jwt:
  secret: 'SECRET'
  expiresIn: 1000000

maps:
  key: 'key'

mail:
  user: 'nidhal.sabbah@gmail.com'
  password: 'password'
